### ISSUE TITLE
Custom prefix

### ISSUE THREAD

**Issue by davyg** [svalat/homelinux#40]
Is it possible to use another prefix than $HOME/usr ? I tried to put another one when I launched
"make install". It seemed to work but running "$PREFIX/bin/hl env" output all the paths with
$HOME/usr as prefix and not the one I gave.

**Comment by svalat** [comment]
You need to setup ~/.homelinux.json (copy userconf.json from source) and setup the value.

If the file is not present I use $HOME/usr by default, but you are right, I must patch to replace this by PREFIX used by make install. Thank you for the remark.
